name: my-first-workflow

on: push


jobs: 
    firstJob: 
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
              
            - name: Welcome message
              run: echo "welcome to githubaction"
            
            - name: list-files 
              run: ls 
            
            - name: Read file
              run: cat README.md
