name: generate ASCII artwork 

on: push


jobs: 
    asci-artwrokjob: 
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
              
            - name: list  out repo files 
              run: ls -ltra

            - name: executing shell script 
              run: ./ascii.sh
              
            