name: generate ASCII artwork 

on: push


jobs: 
    first:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: install cowsay program 
              run: sudo apt-get install cowsay -y 

            - name: Generate ascii artwork
              run: cowsay -f dragon "run for teh cover I am a DRAGONG ...RWAR" >>dragon.txt

            - name: sleep for 30 second
              run: sleep 30 
    
    second-job: 
        needs: first
        runs-on: ubunut-latest
        steps: 
           - name: sleep for 10 second 
             run: sleep 10

           - name: test file exists 
             run: grep -i "dragon" dragon.txt

    third-job: 
        needs: first
        runs-on: ubuntu-latest 

        steps:
           - name: read file 
             run: cat dragon.txt